---
- hosts: builder
  tasks:
  - name: upload image to glance
    os_image:
      state: present
      auth: '{{ osp_user }}'
      name: '{{ glance_image.name }}'
      filename: '{{ glance_image.file }}'
      container_format: bare
      disk_format: '{{ glance_image.disk }}'
    tags:
    - qcow2
    - glance
  - name: create a security group
    os_security_group:
      state: present
      auth: '{{ osp_user }}'
      name: '{{ osp_priv.security_group }}'
  - name: open up ping
    os_security_group_rule:
      state: present
      auth: '{{ osp_user }}'
      security_group: '{{ osp_priv.security_group }}'
      protocol: icmp
      remote_ip_prefix: 0.0.0.0/0
    tags:
    - secgroups
  - name: ...and ssh
    os_security_group_rule:
      state: present
      auth: '{{ osp_user }}'
      security_group: '{{ osp_priv.security_group }}'
      protocol: tcp
      port_range_min: 22
      port_range_max: 22
      remote_ip_prefix: 0.0.0.0/0
    tags:
    - secgroups
  - name: create private network
    os_network:
      state: present
      auth: '{{ osp_user }}'
      name: '{{ osp_priv.net_name }}'
    tags:
    - priv_nets
  - name: create private subnet
    os_subnet:
      state: present
      auth: '{{ osp_user }}'
      name: '{{ osp_priv.subnet_name }}'
      network_name: '{{ osp_priv.net_name }}'
      cidr: '{{ osp_priv.cidr }}'
      dns_nameservers: '{{ osp_priv.dns }}'
      enable_dhcp: True
    tags:
    - priv_nets
  - name: create private router
    os_router:
      state: present
      auth: '{{ osp_user }}'
      name: '{{ osp_priv.router_name }}'
      interfaces: '{{ osp_priv.subnet_name }}'
      network: '{{ osp_admin_net.name }}'
    tags:
    - priv_nets
  - name: boot an instance in nova
    os_server:
      state: present
      auth: '{{ osp_user }}'
      name: '{{ instance_name }}'
      image: '{{ image_name }}'
      key_name: '{{ osp_user.username }}'
      flavor: '{{ nova_flavor }}'
      floating_ip_pools: '{{ osp_admin_net.name }}'
    register: os_server
  - debug: var=os_server.server.accessIPv4
